version: '3'

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"

  zipkin:
    image: "openzipkin/zipkin:latest"
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=mem
    depends_on:
      - redis
      - mongodb
  sqlserver:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "YourPassword123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
